========== Linting Errors ==========
0
========== End of Linting ==========
============================================
Test Run Started: 2025-07-02 14:07:28
--------------------------------------------
============================= test session starts ==============================
platform linux -- Python 3.10.18, pytest-8.3.5, pluggy-1.6.0 -- /opt/hostedtoolcache/Python/3.10.18/x64/bin/python
cachedir: .pytest_cache
metadata: {'Python': '3.10.18', 'Platform': 'Linux-6.11.0-1015-azure-x86_64-with-glibc2.39', 'Packages': {'pytest': '8.3.5', 'pluggy': '1.6.0'}, 'Plugins': {'metadata': '3.1.1', 'rerunfailures': '15.1', 'html': '4.1.1', 'Faker': '37.4.0', 'xdist': '3.8.0'}, 'CI': 'true', 'JAVA_HOME': '/usr/lib/jvm/temurin-17-jdk-amd64'}
rootdir: /home/runner/work/Mocha_accounting/Mocha_accounting
plugins: metadata-3.1.1, rerunfailures-15.1, html-4.1.1, Faker-37.4.0, xdist-3.8.0
collecting ... collected 0 items / 1 error

==================================== ERRORS ====================================
_____________________ ERROR collecting tests/test_login.py _____________________
ImportError while importing test module '/home/runner/work/Mocha_accounting/Mocha_accounting/tests/test_login.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_login.py:13: in <module>
    from pages.login_page import LoginPage
pages/login_page.py:4: in <module>
    from actions.actions import Actions
actions/actions.py:3: in <module>
    from asyncio import timeout
E   ImportError: cannot import name 'timeout' from 'asyncio' (/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/asyncio/__init__.py)
- Generated html report: file:///home/runner/work/Mocha_accounting/Mocha_accounting/C%3A%5CUsers%5CTaurus13%5CPycharmProjects%5CPythonProject%5Creports/20250702_140729/report.html -
=========================== short test summary info ============================
ERROR tests/test_login.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.15s ===============================
--------------------------------------------
Test Run Finished: 2025-07-02 14:07:30
Duration: 2 seconds
Status: FAILURE
Exit Code: 2
============================================
========== Linting Errors ==========
0
========== End of Linting ==========
============================================
Test Run Started: 2025-07-02 14:40:01
--------------------------------------------
============================= test session starts ==============================
platform linux -- Python 3.10.18, pytest-8.3.5, pluggy-1.6.0 -- /opt/hostedtoolcache/Python/3.10.18/x64/bin/python
cachedir: .pytest_cache
metadata: {'Python': '3.10.18', 'Platform': 'Linux-6.11.0-1015-azure-x86_64-with-glibc2.39', 'Packages': {'pytest': '8.3.5', 'pluggy': '1.6.0'}, 'Plugins': {'metadata': '3.1.1', 'rerunfailures': '15.1', 'html': '4.1.1', 'Faker': '37.4.0', 'xdist': '3.8.0'}, 'CI': 'true', 'JAVA_HOME': '/usr/lib/jvm/temurin-17-jdk-amd64'}
rootdir: /home/runner/work/Mocha_accounting/Mocha_accounting
plugins: metadata-3.1.1, rerunfailures-15.1, html-4.1.1, Faker-37.4.0, xdist-3.8.0
collecting ... collected 0 items / 20 errors

==================================== ERRORS ====================================
___________________ ERROR collecting tests/test_all_sales.py ___________________
ImportError while importing test module '/home/runner/work/Mocha_accounting/Mocha_accounting/tests/test_all_sales.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_all_sales.py:7: in <module>
    from pages.all_sales_page import AllSales
pages/all_sales_page.py:10: in <module>
    from actions.actions import Actions
actions/actions.py:3: in <module>
    from asyncio import timeout
E   ImportError: cannot import name 'timeout' from 'asyncio' (/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/asyncio/__init__.py)
______________ ERROR collecting tests/test_create_credit_memo.py _______________
ImportError while importing test module '/home/runner/work/Mocha_accounting/Mocha_accounting/tests/test_create_credit_memo.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_create_credit_memo.py:5: in <module>
    from pages.create_credit_memo import CreditMemo
pages/create_credit_memo.py:14: in <module>
    from actions.actions import Actions
actions/actions.py:3: in <module>
    from asyncio import timeout
E   ImportError: cannot import name 'timeout' from 'asyncio' (/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/asyncio/__init__.py)
________________ ERROR collecting tests/test_create_invoice.py _________________
ImportError while importing test module '/home/runner/work/Mocha_accounting/Mocha_accounting/tests/test_create_invoice.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_create_invoice.py:4: in <module>
    from pages.create_invoice import Create_Invoice
pages/create_invoice.py:7: in <module>
    from actions.actions import Actions
actions/actions.py:3: in <module>
    from asyncio import timeout
E   ImportError: cannot import name 'timeout' from 'asyncio' (/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/asyncio/__init__.py)
____________ ERROR collecting tests/test_create_product_service.py _____________
ImportError while importing test module '/home/runner/work/Mocha_accounting/Mocha_accounting/tests/test_create_product_service.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_create_product_service.py:4: in <module>
    from self import driver
E   ModuleNotFoundError: No module named 'self'
_____________ ERROR collecting tests/test_create_refund_receipt.py _____________
ImportError while importing test module '/home/runner/work/Mocha_accounting/Mocha_accounting/tests/test_create_refund_receipt.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_create_refund_receipt.py:5: in <module>
    from pages.create_refund_receipt import RefundReceipt
pages/create_refund_receipt.py:14: in <module>
    from actions.actions import Actions
actions/actions.py:3: in <module>
    from asyncio import timeout
E   ImportError: cannot import name 'timeout' from 'asyncio' (/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/asyncio/__init__.py)
_____________ ERROR collecting tests/test_create_sales_receipt.py ______________
ImportError while importing test module '/home/runner/work/Mocha_accounting/Mocha_accounting/tests/test_create_sales_receipt.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_create_sales_receipt.py:5: in <module>
    from pages.create_sales_receipt import SalesReceipt
pages/create_sales_receipt.py:14: in <module>
    from actions.actions import Actions
actions/actions.py:3: in <module>
    from asyncio import timeout
E   ImportError: cannot import name 'timeout' from 'asyncio' (/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/asyncio/__init__.py)
________________ ERROR collecting tests/test_createcustomer.py _________________
ImportError while importing test module '/home/runner/work/Mocha_accounting/Mocha_accounting/tests/test_createcustomer.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_createcustomer.py:3: in <module>
    from pages.create_customer import CreateCustomer
pages/create_customer.py:17: in <module>
    from actions.actions import Actions
actions/actions.py:3: in <module>
    from asyncio import timeout
E   ImportError: cannot import name 'timeout' from 'asyncio' (/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/asyncio/__init__.py)
_________________ ERROR collecting tests/test_customer_list.py _________________
ImportError while importing test module '/home/runner/work/Mocha_accounting/Mocha_accounting/tests/test_customer_list.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_customer_list.py:7: in <module>
    from pages.customer_list import CustomerList
pages/customer_list.py:11: in <module>
    from actions.actions import Actions
actions/actions.py:3: in <module>
    from asyncio import timeout
E   ImportError: cannot import name 'timeout' from 'asyncio' (/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/asyncio/__init__.py)
___________ ERROR collecting tests/test_customer_transaction_list.py ___________
ImportError while importing test module '/home/runner/work/Mocha_accounting/Mocha_accounting/tests/test_customer_transaction_list.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_customer_transaction_list.py:7: in <module>
    from pages.customer_list import CustomerList
pages/customer_list.py:11: in <module>
    from actions.actions import Actions
actions/actions.py:3: in <module>
    from asyncio import timeout
E   ImportError: cannot import name 'timeout' from 'asyncio' (/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/asyncio/__init__.py)
___________ ERROR collecting tests/test_expense/test_bill_payment.py ___________
ImportError while importing test module '/home/runner/work/Mocha_accounting/Mocha_accounting/tests/test_expense/test_bill_payment.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_expense/test_bill_payment.py:5: in <module>
    from pages.expenses.bill_payment import BillPayment
pages/expenses/bill_payment.py:15: in <module>
    from actions.actions import Actions
actions/actions.py:3: in <module>
    from asyncio import timeout
E   ImportError: cannot import name 'timeout' from 'asyncio' (/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/asyncio/__init__.py)
___________ ERROR collecting tests/test_expense/test_create_bill.py ____________
ImportError while importing test module '/home/runner/work/Mocha_accounting/Mocha_accounting/tests/test_expense/test_create_bill.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_expense/test_create_bill.py:7: in <module>
    from pages.expenses.create_bill import Create_Bill
pages/expenses/create_bill.py:11: in <module>
    from actions.actions import Actions
actions/actions.py:3: in <module>
    from asyncio import timeout
E   ImportError: cannot import name 'timeout' from 'asyncio' (/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/asyncio/__init__.py)
___________ ERROR collecting tests/test_expense/test_create_check.py ___________
ImportError while importing test module '/home/runner/work/Mocha_accounting/Mocha_accounting/tests/test_expense/test_create_check.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_expense/test_create_check.py:4: in <module>
    from pages.expenses.create_check import Create_Check
pages/expenses/create_check.py:11: in <module>
    from actions.actions import Actions
actions/actions.py:3: in <module>
    from asyncio import timeout
E   ImportError: cannot import name 'timeout' from 'asyncio' (/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/asyncio/__init__.py)
__________ ERROR collecting tests/test_expense/test_create_expense.py __________
ImportError while importing test module '/home/runner/work/Mocha_accounting/Mocha_accounting/tests/test_expense/test_create_expense.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_expense/test_create_expense.py:7: in <module>
    from pages.expenses.create_expense import Create_Expense
pages/expenses/create_expense.py:11: in <module>
    from actions.actions import Actions
actions/actions.py:3: in <module>
    from asyncio import timeout
E   ImportError: cannot import name 'timeout' from 'asyncio' (/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/asyncio/__init__.py)
______ ERROR collecting tests/test_expense/test_create_purchase_order.py _______
ImportError while importing test module '/home/runner/work/Mocha_accounting/Mocha_accounting/tests/test_expense/test_create_purchase_order.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_expense/test_create_purchase_order.py:5: in <module>
    from pages.expenses.create_purchase_order import Create_Purchase_Order
pages/expenses/create_purchase_order.py:11: in <module>
    from actions.actions import Actions
actions/actions.py:3: in <module>
    from asyncio import timeout
E   ImportError: cannot import name 'timeout' from 'asyncio' (/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/asyncio/__init__.py)
__________ ERROR collecting tests/test_expense/test_create_vendor.py ___________
ImportError while importing test module '/home/runner/work/Mocha_accounting/Mocha_accounting/tests/test_expense/test_create_vendor.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_expense/test_create_vendor.py:7: in <module>
    from pages.expenses.create_vendor import Create_Vendor
pages/expenses/create_vendor.py:9: in <module>
    from actions.actions import Actions
actions/actions.py:3: in <module>
    from asyncio import timeout
E   ImportError: cannot import name 'timeout' from 'asyncio' (/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/asyncio/__init__.py)
_______ ERROR collecting tests/test_expense/test_create_vendor_credit.py _______
ImportError while importing test module '/home/runner/work/Mocha_accounting/Mocha_accounting/tests/test_expense/test_create_vendor_credit.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_expense/test_create_vendor_credit.py:5: in <module>
    from pages.expenses.create_vendor_credit import Create_Vendor_Credit
pages/expenses/create_vendor_credit.py:11: in <module>
    from actions.actions import Actions
actions/actions.py:3: in <module>
    from asyncio import timeout
E   ImportError: cannot import name 'timeout' from 'asyncio' (/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/asyncio/__init__.py)
___________ ERROR collecting tests/test_expense/test_expense_list.py ___________
ImportError while importing test module '/home/runner/work/Mocha_accounting/Mocha_accounting/tests/test_expense/test_expense_list.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_expense/test_expense_list.py:7: in <module>
    from pages.expenses.expense_list import  ExpenseList
pages/expenses/expense_list.py:16: in <module>
    from actions.actions import Actions
actions/actions.py:3: in <module>
    from asyncio import timeout
E   ImportError: cannot import name 'timeout' from 'asyncio' (/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/asyncio/__init__.py)
__________________ ERROR collecting tests/test_invoce_list.py __________________
ImportError while importing test module '/home/runner/work/Mocha_accounting/Mocha_accounting/tests/test_invoce_list.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_invoce_list.py:7: in <module>
    from pages.invoices_list import InvoicesList
pages/invoices_list.py:11: in <module>
    from actions.actions import Actions
actions/actions.py:3: in <module>
    from asyncio import timeout
E   ImportError: cannot import name 'timeout' from 'asyncio' (/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/asyncio/__init__.py)
_____________________ ERROR collecting tests/test_login.py _____________________
ImportError while importing test module '/home/runner/work/Mocha_accounting/Mocha_accounting/tests/test_login.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_login.py:13: in <module>
    from pages.login_page import LoginPage
pages/login_page.py:4: in <module>
    from actions.actions import Actions
actions/actions.py:3: in <module>
    from asyncio import timeout
E   ImportError: cannot import name 'timeout' from 'asyncio' (/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/asyncio/__init__.py)
________________ ERROR collecting tests/test_receive_payment.py ________________
ImportError while importing test module '/home/runner/work/Mocha_accounting/Mocha_accounting/tests/test_receive_payment.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_receive_payment.py:5: in <module>
    from pages.receive_payment import ReceivePayment
pages/receive_payment.py:15: in <module>
    from actions.actions import Actions
actions/actions.py:3: in <module>
    from asyncio import timeout
E   ImportError: cannot import name 'timeout' from 'asyncio' (/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/asyncio/__init__.py)
- Generated html report: file:///home/runner/work/Mocha_accounting/Mocha_accounting/C%3A%5CUsers%5CTaurus13%5CPycharmProjects%5CPythonProject%5Creports/20250702_144004/report.html -
=========================== short test summary info ============================
ERROR tests/test_all_sales.py
ERROR tests/test_create_credit_memo.py
ERROR tests/test_create_invoice.py
ERROR tests/test_create_product_service.py
ERROR tests/test_create_refund_receipt.py
ERROR tests/test_create_sales_receipt.py
ERROR tests/test_createcustomer.py
ERROR tests/test_customer_list.py
ERROR tests/test_customer_transaction_list.py
ERROR tests/test_expense/test_bill_payment.py
ERROR tests/test_expense/test_create_bill.py
ERROR tests/test_expense/test_create_check.py
ERROR tests/test_expense/test_create_expense.py
ERROR tests/test_expense/test_create_purchase_order.py
ERROR tests/test_expense/test_create_vendor.py
ERROR tests/test_expense/test_create_vendor_credit.py
ERROR tests/test_expense/test_expense_list.py
ERROR tests/test_invoce_list.py
ERROR tests/test_login.py
ERROR tests/test_receive_payment.py
!!!!!!!!!!!!!!!!!!! Interrupted: 20 errors during collection !!!!!!!!!!!!!!!!!!!
============================== 20 errors in 0.56s ==============================
--------------------------------------------
Test Run Finished: 2025-07-02 14:40:05
Duration: 4 seconds
Status: FAILURE
Exit Code: 2
============================================
