=== REGISTRATION TESTS STARTED: 2025-10-19 03:56:46 ===
============================= test session starts ==============================
platform linux -- Python 3.13.8, pytest-8.3.5, pluggy-1.6.0 -- /opt/hostedtoolcache/Python/3.13.8/x64/bin/python
cachedir: .pytest_cache
metadata: {'Python': '3.13.8', 'Platform': 'Linux-6.14.0-1012-azure-x86_64-with-glibc2.39', 'Packages': {'pytest': '8.3.5', 'pluggy': '1.6.0'}, 'Plugins': {'metadata': '3.1.1', 'xdist': '3.8.0', 'rerunfailures': '16.1', 'Faker': '37.11.0', 'html': '4.1.1'}, 'CI': 'true', 'JAVA_HOME': '/usr/lib/jvm/temurin-17-jdk-amd64'}
rootdir: /home/runner/work/Mocha_accounting/Mocha_accounting
plugins: metadata-3.1.1, xdist-3.8.0, rerunfailures-16.1, Faker-37.11.0, html-4.1.1
collecting ... collected 0 items / 1 error

==================================== ERRORS ====================================
___________ ERROR collecting tests/test_signup_login/test_sign_up.py ___________
ImportError while importing test module '/home/runner/work/Mocha_accounting/Mocha_accounting/tests/test_signup_login/test_sign_up.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.13.8/x64/lib/python3.13/importlib/__init__.py:88: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_signup_login/test_sign_up.py:8: in <module>
    from utilities.get_mail_otp import get_latest_otp_email
utilities/get_mail_otp.py:8: in <module>
    from bs4 import BeautifulSoup
E   ModuleNotFoundError: No module named 'bs4'
- Generated html report: file:///home/runner/work/Mocha_accounting/Mocha_accounting/C%3A%5CUsers%5CTaurus13%5CPycharmProjects%5CPythonProject%5Creports/20251019_035647/report.html -
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.15s ===============================
=== REGISTRATION TESTS COMPLETED ===
Exit Code: 2
